[package]
name = "rt"
version = "0.1.0"
authors = ["Lauri Gustafsson <me@gustafla.space>"]
edition = "2018"

[dependencies]
crossbeam = "0.8.0"
glam = "0.15.2"
image = "0.23.14"
num_cpus = "1.13.0"

[profile.dev]
opt-level = 2

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
